service:
  ms1: http://localhost:8081
#  ms2: http://localhost:8082

#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: ms1
#          uri: lb://MS1
#          predicates:
#            - Path=/ms1/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
    registry-fetch-interval-seconds: 10 # Gateway는 기본적으로 30초간격으로 Eureka에서 인스턴스 목록을 갱신하지만 해당 옵션을 통해 갱신 시간 단축 가능